Add Vitest
NatVIII/rva.rip pull request #8
Opened 2023-12-09 17:12 UTC by DanielKim1

Set up Vitest, the recommended test runner for Nuxt (see https://nuxt.com/docs/getting-started/testing#features)

2023-12-09 17:13 UTC, DanielKim1 commented on api/fetchImage.js
> +import axios from "axios";
> Vitest doesn't intercept require, so it is not possible to mock a module that was loaded with require

https://github.com/vitest-dev/vitest/discussions/3134#discussioncomment-5520134

2023-12-12 17:07 UTC, NatVIII commented
Testing the functions of this website is something that it sorely lacks, I really appreciate any attempt to move towards better testing and fixing of features. Will work on approving now <3

2023-12-12 18:41 UTC, NatVIII requested changes
Rewrite the const and import stuff in api/fetchImage.js.

Images seem not to load in eventModals anymore, but I don't have an embedded way of knowing what type of error. It's very likely related to that change though.

2023-12-22 23:44 UTC, DanielKim1 commented
fetchImage changes in #10 will require different tests, will add tests in a new PR

2023-12-22 23:44 UTC, closed without merging